name: fara_chat
description: "Simple chat app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+20250301

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  #state managment
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  cupertino_icons: ^1.0.8

  #router
  go_router: ^14.8.0

  #localization
  intl: ^0.19.0
  flutter_localization: ^0.3.1

  #supabase
  supabase_flutter: ^2.8.4

  #utils
  timeago: ^3.7.0
  image_picker: ^1.1.2
  file_picker: ^9.0.1
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  collection: ^1.19.0

  #audio
  record: ^5.2.1
  just_audio: ^0.9.46 
  audio_session: ^0.1.25

  #video
  video_player: ^2.9.3

  #database
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.31

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.25.2
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.5
  build_runner: ^2.4.15

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/supabase/.env

  fonts:
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf

    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-Bold.ttf
          weight: 600
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 700